package com.kamesuta.mc.signpic.shortening;

public class ShorteningReference {
	public static final String WASD = "rO0ABXNyADBjb20ua2FtZXN1dGEubWMuc2lnbnBpYy5zaG9ydGVuaW5nLlNob3J0ZW5pbmdLZXkAAAAAAAAAAQIAAkwAB3BpY3R1cmV0ABJMamF2YS9sYW5nL1N0cmluZztMAARzaWducQB+AAF4cHQAJ0FJemFTeUNiSkM0elRxdFNSTUdyTWoxQzRfak9lc0RockItVE91TXQAKDlhMmJhZThkMDM4NTg3MGRmYWQ5ZTRhZDBiODc0YzQ2OGRmMDQxNDk=";
}
