package com.kamesuta.mc.signpic.shortening;

public class ShorteningReference {
	public static final String WASD = "rO0ABXNyADFjb20ua2FtZXN1dGEubWMuc2lnbnBpYy5zaG9ydGVuaW5nLklTaG9ydGVuaW5nS2V5AAAAAAAAAAECAAJMAAdwaWN0dXJldAASTGphdmEvbGFuZy9TdHJpbmc7TAAEc2lnbnEAfgABeHB0ACdBSXphU3lDYkpDNHpUcXRTUk1Hck1qMUM0X2pPZXNEaHJCLVRPdU10ACg5YTJiYWU4ZDAzODU4NzBkZmFkOWU0YWQwYjg3NGM0NjhkZjA0MTQ5";
}
